server:
  port: 9192
  servlet:
    context-path: /canteen
spring:
  application:
    name: fyp-api
  datasource:
    url: jdbc:postgresql://localhost:5432/canteen_management
    username: postgres
    password: admin


    driver-class-name: org.postgresql.Driver
    hikari:
      minimum-idle: 5
      maximum-pool-size: 300
      connection-timeout: 600000
      idle-timeout: 60000
      max-lifetime: 1800
      leak-detection-threshold: 600000
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    database: postgresql
    properties:
      hibernate:
        jdbc:
          lob:
            non_contextual_creation: true
      format_sql: true
    open-in-view: false


  security:
    oauth2:
      client:
        registration:
          google:
            client-id: 746907184110-vm60s3kv0ofk1soqg2l5qptm60t82it0.apps.googleusercontent.com
            client-secret: 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

mybatis:
  mapper-locations: classpath*:/mybatis/*.xml # Tells mybatis to look in resources/mybatis for XML com.infodev.oauthserver.mappers
  type-aliases-package: fyp.canteen.fypcore.pojo.* # Tells mybatis to look for our POJO class in the right package
  configuration:
    map-underscore-to-camel-case: true #converts underscore of db into camelcase